# app/pages/foundation/02_tokenization.py

import streamlit as st
import numpy as np
import plotly.express as px
from transformers import GPT2Tokenizer
import pandas as pd
import tiktoken

st.set_page_config(page_title="Tokenization | llms102", layout="wide")

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

COLORS = [
    "#FF6B6B", "#4ECDC4", "#45B7D1", "#96CEB4",
    "#FFEAA7", "#DDA0DD", "#98D8C8", "#F7DC6F"
]

# ─── Hero ────────────────────────────────────────────────────────────────────

st.title("Tokenization")
st.caption("How we translate language space into numerical space")

st.markdown("")  # 2 sentences — what this page covers

st.divider()

# ─── 1. What is tokenization? ────────────────────────────────────────────────

st.header("Intuition behind tokenization")

st.markdown("""
So we understand that languages have statistical properties, and that these properties can be exploited to create a language model. However, machine learning requires numbers to operate, not text. So we need to find a way to describe languages as numbers in order to process them. 
            
Tokenization is exactly this process. We divide the language space up into chunks that are represented in the numerical space. 
            
How we present this distribution matters a lot. For instance, let's say that we had to find a statistical method to distinguish cars. We could create a table that considers body length, color, and wheel size, the combination of which is likely to be sufficiently unique to distinguish between cars. However, we lose out on any possible information related to say engine performance. 
            
Likewise, in language, the way we split text also has larger downstream effects. For us to be able to efficiently exploit the statistics of language, we need an effective representation in the numerical space.
""")  

st.divider()

# ─── Section 1: Linguistic Properties ────────────────────────────────────────

st.header("Properties of languages")

st.markdown("""
This section is optional, but highly recommended to read. Languages have both varying linguistic and statistical properties, which are important to understand when we design custom tokenizers. It's unlikely you ever will, but doesn't hurt to know. 
            
The only notion we need to move ahead with is that languages contain statistical properties, and we need to analyze them in order to effectively represent them. 
            
Additionally, please note that this is only an introduction. These fields are vast, with centuries of research on them. However, this appendix should provide you with some baseline knowledge. 

> **DISCLAIMER**: The content here was largely generated by AI
""")

with st.expander("Appendix: Language Properties Primer", expanded=False):
    tab1, tab2 = st.tabs(["Linguistic Properties", "Statistical Properties"])

    with tab1:

        # ── Script & Orthography ──────────────────────────────────────────────

        st.subheader("Script & Orthography Diversity")

        st.markdown("""
        A **script** is the visual system used to write a language — the set of symbols and the rules 
        for how they are arranged. An **orthography** is the specific conventions for using that script 
        in a particular language (spelling rules, punctuation, capitalisation, and so on).

        Writing systems encode language at different levels of granularity. Some encode individual sounds, 
        others encode syllables, and others encode whole words or concepts. This directly determines what 
        a single "character" means, and how much information a single token carries.

        There are five major types of writing system:
        - An **alphabet** encodes both consonant and vowel sounds as separate letters. Examples include the Latin script (used by English, French, Spanish) and Cyrillic (used by Russian).
        - An **abjad** encodes only consonant sounds — vowels are either omitted or written as optional marks. Examples include Arabic and Hebrew.
        - An **abugida** (also called an alphasyllabary) encodes consonants as the base character, with vowels indicated by diacritics (small attached marks). Examples include Devanagari (used for Hindi) and Ethiopic.
        - A **syllabary** encodes whole syllables as single characters. Examples include Japanese Hiragana and Katakana.
        - A **logography** encodes whole morphemes or words as single characters. Chinese Hanzi is the most widely used example.
        """)

        st.table(pd.DataFrame({
            "Script type":            ["Alphabet",              "Abjad",                        "Abugida",                               "Syllabary",                                         "Logography"                          ],
            "Encodes":                ["Consonants and vowels", "Consonants (vowels optional)",  "Consonants with diacritic vowels",      "Syllables",                                         "Morphemes or words"                  ],
            "Examples":               ["Latin, Cyrillic",       "Arabic, Hebrew",                "Devanagari, Ethiopic",                  "Hiragana, Katakana",                                "Chinese Hanzi"                       ],
            "Tokenization challenge": ["Well studied",          "Vowel omission inflates forms", "Diacritics expand character vocabulary","Syllable boundaries do not equal morpheme boundaries","Characters are approximately equal to words"],
        }))

        st.divider()

        # ── Morphology & Compositionality ─────────────────────────────────────

        st.subheader("Morphology and Compositionality")

        st.markdown("""
        **Morphology** is the study of the internal structure of words. The smallest meaningful unit in 
        a language is called a **morpheme**. Unlike a syllable, which is purely a unit of sound, a morpheme 
        carries meaning. For example, the word *"unbelievable"* contains three morphemes:

        - *un-* — a prefix meaning negation
        - *believe* — the root, carrying the core meaning
        - *-able* — a suffix meaning "can be done"

        This property is called **compositionality** — the meaning of a word is composed from the meanings 
        of its parts. A tokenizer that respects morpheme boundaries lets the model generalise across word 
        forms: if it has learned that *"un-"* means negation from *"undo"*, it can apply that to *"unbelievable"* 
        without having seen it before. A tokenizer that does not respect these boundaries forces the model 
        to re-learn the same meaning under many different surface forms.

        Select a word below to see how it breaks down into morphemes:
        """)

        MORPHEME_DB = {
            "unbelievable": [("un-",   "negation"),      ("believe", "root"),  ("-able", "can be done")  ],
            "reconnected":  [("re-",   "again"),          ("connect", "root"),  ("-ed",   "past tense")   ],
            "preprocessing":[("pre-",  "before"),         ("process", "root"),  ("-ing",  "ongoing action")],
            "unhappiness":  [("un-",   "negation"),       ("happi",   "root"),  ("-ness", "state of")     ],
            "misunderstand":[("mis-",  "wrongly"),        ("under-",  "under"), ("stand", "root")         ],
        }

        word_choice = st.selectbox("Choose a word to decompose:", options=list(MORPHEME_DB.keys()))
        morphemes = MORPHEME_DB[word_choice]
        cols = st.columns(len(morphemes))
        for col, (morpheme, role) in zip(cols, morphemes):
            col.metric(label=role, value=morpheme)

        st.divider()

        # ── Syntax & Word Order ───────────────────────────────────────────────

        st.subheader("Syntax and Word Order")

        st.markdown("""
        **Syntax** is the set of rules that govern how words are arranged to form sentences. One of the 
        most important syntactic properties of a language is its **canonical word order** — the default 
        sequence in which a subject, verb, and object appear in a simple sentence.

        - **Subject-Verb-Object**: The cat chased the mouse. *(English, Mandarin)*
        - **Subject-Object-Verb**: The cat the mouse chased. *(Japanese, Turkish)*
        - **Verb-Subject-Object**: Chased the cat the mouse. *(Arabic, Welsh)*

        In languages with a **fixed word order** like English, grammatical relationships are encoded 
        positionally — move a word and you change the meaning. In **free word order** languages like 
        Russian or Turkish, grammatical relationships are instead encoded through **case markers** — 
        morphemes attached to words that signal their grammatical role (subject, object, and so on). 
        A tokenizer that merges or discards these suffixes removes the very information the model needs 
        to understand the sentence.
        """)

        st.table(pd.DataFrame({
            "Language":       ["English",               "Mandarin",              "Japanese",              "Arabic",                "Russian",                        "Turkish"                        ],
            "Word order":     ["Subject-Verb-Object",   "Subject-Verb-Object",   "Subject-Object-Verb",   "Verb-Subject-Object",   "Subject-Verb-Object (flexible)", "Subject-Object-Verb (flexible)" ],
            "Free order?":    ["No",                    "No",                    "No",                    "No",                    "Yes",                            "Yes"                            ],
            "Case marking?":  ["Minimal",               "None",                  "Particles",             "Yes",                   "Rich",                           "Rich"                           ],
        }))

        st.divider()

        # ── Ambiguity & Context-Dependence ────────────────────────────────────

        st.subheader("Ambiguity and Context-Dependence")

        st.markdown("""
        Many words carry more than one meaning. **Polysemy** refers to a single word having multiple 
        related meanings — for example, *"head"* can mean the top of a body, the head of an organisation, 
        or the head of a river. **Homonymy** refers to words that are spelled identically but have 
        completely unrelated meanings — for example, *"bank"* (a financial institution) and *"bank"* 
        (the edge of a river) share no meaningful connection.

        This is a fundamental challenge for tokenization: a token is assigned a single identifier 
        regardless of which meaning is intended. The model has no disambiguation at the token level — 
        it must rely entirely on the surrounding context window to determine which sense is meant.
        """)

        st.table(pd.DataFrame({
            "Word":       ["bank",                  "fine",           "lead",           "bark",               "crane"             ],
            "Meaning A":  ["Financial institution", "A penalty",      "A metal element","Tree covering",      "A bird"            ],
            "Meaning B":  ["Edge of a river",       "Satisfactory",   "To guide",       "Sound a dog makes",  "A lifting machine" ],
            "Type":       ["Homonymy",              "Polysemy",       "Homonymy",       "Homonymy",           "Homonymy"          ],
        }))

        st.divider()

        # ── Semantic Compositionality ─────────────────────────────────────────

        st.subheader("Semantic Compositionality and Fixed Expressions")

        st.markdown("""
        We established above that words are compositional — their meaning is built from morphemes. 
        The same principle should apply at the phrase level: the meaning of a phrase should be 
        derivable from its words. Most of the time this holds, but natural language has many exceptions.

        An **idiom** is a phrase whose meaning cannot be derived from its individual words — 
        *"kick the bucket"* has nothing to do with kicking or buckets; it means to die. A 
        **collocation** is a pair of words that habitually appear together and where only one 
        combination sounds natural — you *"make a decision"*, not *"do a decision"*. A 
        **named entity** is a proper noun referring to a specific person, place, or organisation — 
        *"New York"* is not a new thing that is also York; it is a single indivisible concept.

        Most tokenizers have no mechanism to identify or preserve these multi-word units. The model 
        receives them as independent tokens and must recover their combined meaning purely from 
        co-occurrence statistics in training data.
        """)

        st.table(pd.DataFrame({
            "Expression":       ["kick the bucket", "New York",      "make a decision",  "under the weather", "piece of cake" ],
            "Type":             ["Idiom",           "Named entity",  "Collocation",      "Idiom",             "Idiom"         ],
            "What tokens show": ["kick and bucket", "New and York",  "make and decision","under and weather", "piece and cake"],
            "Actual meaning":   ["To die",          "A city",        "To decide",        "Feeling unwell",    "Something easy"],
        }))

    with tab2:

        # ── Zipf's Law ────────────────────────────────────────────────────────

        st.subheader("Zipf's Law")

        st.markdown("""
        Word frequencies follow a power law — a small number of words account for the vast majority 
        of all usage. We covered this in depth in the [previous article](#). The key takeaway here: 
        because frequency is so skewed, a tokenizer that allocates vocabulary slots uniformly across 
        words is deeply inefficient. This motivates frequency-aware methods like Byte Pair Encoding.
        """)

        st.divider()

        # ── Heap's Law ────────────────────────────────────────────────────────

        st.subheader("Heap's Law: Vocabulary Growth")

        st.markdown("""
        As you read more text, you keep encountering new words — but at a diminishing rate. This 
        relationship is captured by **Heap's Law**, which states that vocabulary size grows as a 
        power law of corpus size:

        $$V(n) = K \\cdot n^\\beta$$

        where $n$ is the number of tokens seen, $K$ is a scaling constant, and $\\beta$ is the growth 
        rate (typically between 0.4 and 0.6 for English). The implication is stark — no fixed vocabulary 
        is ever complete. New tokens will always appear at test time, which is the core motivation for 
        subword tokenization methods.
        """)

        col1, col2 = st.columns(2)
        with col1:
            K = st.slider("K (scale)", min_value=1, max_value=20, value=10)
        with col2:
            beta = st.slider("β (growth rate)", min_value=0.3, max_value=0.9, value=0.5, step=0.05)

        n_vals = np.linspace(1000, 1_000_000, 300)
        st.line_chart(pd.DataFrame({"Vocabulary size": K * (n_vals ** beta)}, index=n_vals))
        st.caption("Vocabulary never plateaus — it just grows more slowly as the corpus gets larger.")

        st.divider()

        # ── Type-Token Ratio ──────────────────────────────────────────────────

        st.subheader("Type-Token Ratio")

        st.markdown("""
        The **type-token ratio** is a measure of lexical diversity. A **token** is any word occurrence 
        in a text. A **type** is a unique word form. The ratio is simply the number of unique types 
        divided by the total number of tokens. A high type-token ratio means the text uses a wide 
        variety of different words; a low ratio means the same words repeat frequently.

        This varies significantly across languages and domains. Agglutinative languages like Finnish 
        and Turkish have a high type-token ratio because their morphology produces a large number of 
        unique word forms from a smaller set of roots — placing much greater pressure on vocabulary 
        coverage and making out-of-vocabulary problems worse.
        """)

        st.bar_chart(pd.DataFrame({
            "Language or domain":  ["English (news)", "English (social media)", "Finnish", "Turkish", "Arabic", "Mandarin", "Python code"],
            "Approximate type-token ratio": [0.42,    0.62,                     0.68,      0.71,      0.65,     0.35,       0.55        ],
        }).set_index("Language or domain"))
        st.caption("Agglutinative languages (Finnish, Turkish) have high type-token ratios due to extensive morphological inflection.")

        st.divider()

        # ── Compaction & Fertility ────────────────────────────────────────────

        st.subheader("Compaction and Tokenizer Fertility")

        st.markdown("""
        **Tokenizer fertility** measures how many tokens a tokenizer requires to encode a given piece 
        of text. A tokenizer with high fertility for a language produces many tokens per unit of meaning 
        — which increases inference cost, reduces the effective context window, and typically degrades 
        model performance for that language.

        Most large language model tokenizers are trained predominantly on English text. As a result, 
        non-English languages — particularly those using non-Latin scripts — require significantly more 
        tokens to express the same content. Research has found that for some languages, users of English-optimised 
        tokenizers are effectively charged two to ten times more per unit of meaning compared to English speakers.
        """)

        st.bar_chart(pd.DataFrame({
            "Language": ["English", "French", "German", "Russian", "Arabic", "Hindi",  "Thai", "Japanese", "Chinese"],
            "Tokens per 100 characters": [18,  21,       17,        35,       48,       40,     55,         30,        15      ],
        }).set_index("Language"))
        st.caption("Approximate token counts to encode 100 characters using a tokenizer optimised for English. Non-Latin scripts require substantially more tokens for equivalent content.")

st.divider()

st.subheader("What does a tokenizer do?")

st.markdown("""
A tokenizer maps splits of language space to the number space. Each split is assigned a unique ID. Our models only see these IDs, and not the underlying text - this also means that once trained on a specific tokenizer, the model may not work well if the underlying tokenizer is changed. 

The core design problem here is deciding how, when and where the splits occur. For instance, we could use only characters, entire words, or splits of words. Each gives us different statistical properties to exploit. 

We will look into how to evaluate the quality of tokenization in the next section. For now, use the widget below to understand how the splits are occuring. 
""")

sentence = st.text_input("Enter a sentence", value="Tokenization breaks text into pieces.")

mode = st.radio("Tokenization level", ["Character", "Word", "Subword (BPE)"], horizontal=True)

if sentence:
    if mode == "Character":
        tokens = list(sentence)
        ids = [ord(c) for c in tokens]

    elif mode == "Word":
        tokens = sentence.split()
        ids = [abs(hash(t)) % 50000 + 100 for t in tokens]

    elif mode == "Subword (BPE)":
        enc = tiktoken.get_encoding("cl100k_base")
        ids = enc.encode(sentence)
        tokens = [enc.decode([i]) for i in ids]

    col1, col2, col3 = st.columns(3)
    col1.metric("Token count", len(tokens))
    col2.metric("Unique tokens", len(set(tokens)))
    col3.metric("Avg token length", round(sum(len(t) for t in tokens) / len(tokens), 1))

    st.markdown("**Tokens**")
    st.code(" | ".join(repr(t) for t in tokens), language=None)

    st.markdown("**Token table**")
    st.dataframe(
        data={
            "Position": list(range(1, len(tokens) + 1)),
            "Token":    tokens,
            "ID":       ids,
            "Length":   [len(t) for t in tokens],
        },
        use_container_width=True,
        hide_index=True,
    )

st.divider()

st.header("How Do We Evaluate Tokenizers?")

st.markdown("") # brief intro

sections = {
    "Vocabulary and Coverage": [
        "Vocabulary Size",
        "Out-of-Vocabulary Rate",
        "Type-Token Ratio",
    ],
    "Fertility and Efficiency": [
        "Fertility",
        "Compression Ratio",
        "Normalized Sequence Length",
        "Continued Word Ratio",
        "Rényi Efficiency",
    ],
    "Linguistic Alignment": [
        "Morphological Alignment",
        "Cognitive Plausibility",
    ],
    "Downstream Task Performance": [
        "Perplexity",
        "Bits Per Character",
        "Cross-Lingual Transfer Gap",
    ],
}

for section_title, topics in sections.items():
    st.subheader(section_title)
    
    tldr, full = st.tabs(["Intuition", "Full Explanation"])
    with tldr:
        st.markdown("")
    with full:
        st.markdown("")

    st.divider()
# ─── Character, word, subword ─────────────────────────────────────────────

st.header("2. Character, word, and subword tokenization")

st.markdown("")  # study: HuggingFace tokenizer docs
                 # answer: tradeoffs of each, why subword won

col1, col2, col3 = st.columns(3)

col1.markdown("**Character-level**")
col1.markdown("")  # one line — the failure mode

col2.markdown("**Word-level**")
col2.markdown("")  # one line — the failure mode

col3.markdown("**Subword**")
col3.markdown("")  # one line — why it works

st.divider()

# ─── 3. Byte Pair Encoding ───────────────────────────────────────────────────

st.header("3. Byte Pair Encoding — Sennrich et al. (2016)")

st.markdown("")  # study: Sennrich et al. 2016 arxiv 1508.07909
                 # answer: how BPE builds vocabulary iteratively, what a merge rule is

# ── BPE merge widget ──────────────────────────────────────────────────────────

st.subheader("BPE merges — interactive")

st.markdown("")  # one sentence directing the reader

word = st.text_input("Enter a word", value="tokenization")
chars = list(word)

steps = []
current = list(word)
steps.append(("Initial split", list(current)))

pairs = {}
for i in range(len(current) - 1):
    pair = (current[i], current[i+1])
    pairs[pair] = pairs.get(pair, 0) + 1

if pairs:
    best = max(pairs, key=pairs.get)
    merged = []
    i = 0
    while i < len(current):
        if i < len(current) - 1 and (current[i], current[i+1]) == best:
            merged.append(current[i] + current[i+1])
            i += 2
        else:
            merged.append(current[i])
            i += 1
    steps.append((f"Merge: '{best[0]}' + '{best[1]}'", merged))

for step_name, tokens in steps:
    st.markdown(f"**{step_name}**")
    cols = st.columns(len(tokens))
    for i, (col, token) in enumerate(zip(cols, tokens)):
        col.markdown(
            f"<div style='background:{COLORS[i % len(COLORS)]};padding:8px;border-radius:4px;text-align:center;color:black'>{token}</div>",
            unsafe_allow_html=True
        )
    st.markdown("")

st.markdown("""
> Sennrich, R., Haddow, B., & Birch, A. (2016). *Neural Machine Translation of 
> Rare Words with Subword Units.* ACL 2016.
> [arxiv 1508.07909](https://arxiv.org/abs/1508.07909)
""")

st.divider()

# ─── 4. WordPiece & SentencePiece ────────────────────────────────────────────

st.header("4. WordPiece & SentencePiece")

st.markdown("")  # study: Kudo & Richardson 2018 arxiv 1808.06226
                 # answer: how WordPiece differs from BPE, what SentencePiece adds, which models use which

st.markdown("""
> Kudo, T. & Richardson, J. (2018). *SentencePiece: A simple and language 
> independent subword tokenizer.*
> [arxiv 1808.06226](https://arxiv.org/abs/1808.06226)
""")

st.divider()

# ─── 5. Vocabulary size ──────────────────────────────────────────────────────

st.header("5. Vocabulary size and its consequences")

st.markdown("")  # study: reason from first principles
                 # answer: too small vs too large, effect on embedding table size

# ── vocabulary size widget ────────────────────────────────────────────────────

st.subheader("Vocabulary size vs embedding table — interactive")

col1, col2 = st.columns(2)
vocab_size = col1.slider("Vocabulary size", min_value=1000, max_value=100000, value=50000, step=1000)
embedding_dim = col2.slider("Embedding dimension", min_value=64, max_value=4096, value=768, step=64)

params = vocab_size * embedding_dim
size_mb = (params * 4) / (1024 ** 2)

col1, col2, col3 = st.columns(3)
col1.metric("Total parameters", f"{params:,}")
col2.metric("Size (float32)", f"{size_mb:.1f} MB")
col3.metric("% of 125M model", f"{(params / 125e6) * 100:.1f}%")

st.divider()

# ─── 6. Tokenization artifacts ───────────────────────────────────────────────

st.header("6. Tokenization artifacts")

st.markdown("")  # study: observe a real tokenizer
                 # answer: whitespace sensitivity, numbers, code, multilingual

# ── token visualizer widget ───────────────────────────────────────────────────

st.subheader("Token visualizer — interactive")

st.markdown("")  # one sentence directing the reader

user_text = st.text_area(
    "Enter any text",
    value="The quick brown fox jumped over the lazy dog. 1 + 1 = 2.",
    height=100
)

if user_text:
    tokens = tokenizer.encode(user_text)
    token_strings = [tokenizer.decode([t]) for t in tokens]

    st.markdown("**Tokens:**")
    html = ""
    for i, token in enumerate(token_strings):
        color = COLORS[i % len(COLORS)]
        html += f"<span style='background:{color};padding:2px 6px;border-radius:3px;margin:2px;display:inline-block;color:black'>{repr(token)}</span>"
    st.markdown(html, unsafe_allow_html=True)

    col1, col2, col3 = st.columns(3)
    col1.metric("Characters", len(user_text))
    col2.metric("Tokens", len(tokens))
    col3.metric("Chars per token", f"{len(user_text)/len(tokens):.2f}")

st.divider()

# ─── 7. What the model never sees ────────────────────────────────────────────

st.header("7. What the model never sees")

st.markdown("")  # study: reason from first principles
                 # answer: model sees ids not text, what is lost, why tokenization affects capabilities

example = "Hello, world!"
token_ids = tokenizer.encode(example)

st.markdown(f"**Input:** `{example}`")
st.markdown(f"**Token IDs:** `{token_ids}`")
st.markdown(f"**Vocabulary size:** `{tokenizer.vocab_size:,}`")

st.divider()

# ─── Footer ──────────────────────────────────────────────────────────────────

col1, col2 = st.columns([1, 5])
col1.page_link("pages/foundation/03_embeddings.py", label="Next: Embeddings →")

st.markdown("""
**Further reading**
- Sennrich et al. (2016) — [Neural Machine Translation of Rare Words with Subword Units](https://arxiv.org/abs/1508.07909)
- Kudo & Richardson (2018) — [SentencePiece](https://arxiv.org/abs/1808.06226)
- Kudo (2018) — [Subword Regularization](https://arxiv.org/abs/1804.10959)
- [HuggingFace Tokenizer Docs](https://huggingface.co/docs/transformers/tokenizer_summary)
""")